[build-system]
requires = [
  'setuptools'
]
build-backend = 'setuptools.build_meta'

[project]
name = 'numbat'
authors = [
    {name = 'Sami Babigeon', email = 'sbabigeon@quarkslab.com'},
]
description = 'Package that allows users to manipulate a sourcetrail database'
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: POSIX :: Linux',
]
version='0.0.1'

[project.optional-dependencies]
test = [
  'pytest'
]

